name: PR Name check

On: 
  pull_request:
   types: [opened, edited, synchronize]
jobs: 
  pr_lint:
    runs-on: ubuntu-latest
    name: Check PR title 
    steps:
    - name: Run
      run: [[ "${{github.event.pull_request.title }}" =~ ^[A-Z]+-[0-9]+[a-z0-9]*:[[:space:]][a-zA-Z0-9[:space:]-]+]] && exit 0 || exit 1
